### ISSUE TITLE
Add UMD module definition

### ISSUE THREAD

**Issue by azanov** [finom/balalaika#3]
Your library is great! However, you can make it even better by going along with time and add the umd module definition to it, so the usage with Browserify, CommonJS, SystemJS etc. gets easier.

For reference see: https://github.com/umdjs/umd

**Comment by finom** [comment]
Hi. Thank you for this proposition. I love modules and I use AMD in every project I do. But Balalaika is positioned as tiny embedded jQuery alternative. Embedded means that you just copy and paste Balalaika code to your webpage or script. UMD will make Balalaika bigger and I can't see any sense to do it.

If you need to turn it on for AMD, CommonJS or SystemJS it doesn't hard to do it yourself.

**Comment by jt3k** [comment]
+1 for umd-web-amd

**Comment by jt3k** [comment]
упс, сорян. увидел в корне умд. спасибо!
