### ISSUE TITLE
Add delegated events [Request]

### ISSUE THREAD

**Issue by midudev** [finom/balalaika#4]
I think that the way that delegated events are handled are difficult and it become in repeated not useful code. Add an easy way to handle delegated events would be a nice addition to the library.

`$( '#news-readable-container' ).on( 'click', '.news-report-button', function() { } );`

**Comment by finom** [comment]
Hi @miduga 

The idea of Balalaika is little size of code (< 1000 bytes) and fully functional delegated events (eg  with `stopPropagation` etc) is very hard to do (I tried) and it's going to take one more kilobyte. You can look on jQuery code to make sure.

An example in the README is huge but you can use DOM4 to get your code better:

``` js
$('.my-selector').on('click', function(evt) {
  if(this.contains(evt.target.closest('.delegated-selector'))) {
    alert('yep!');
  }
});
```

**Comment by midudev** [comment]
I fully understand. :+1: Then I'm gonna write a plugin to extend the functionality in order to avoid dupe code. Thanks for your reply.
